# 5ms 이상 JDBC 쿼리 기록
spring.jpa.properties.hibernate.log_slow_query=1

# SQL 확인
logging.level.org.hibernate.SQL=DEBUG

# 실제 검색어가 필요할 때만 HIBERNATE_BIND_LOG_LEVEL=TRACE로 활성화
logging.level.org.hibernate.orm.jdbc.bind=${HIBERNATE_BIND_LOG_LEVEL:OFF}
